version: "3.7"

services:
  visitplan:
    build: "."
    command: "visitplan-service"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: prestixpress
      POSTGRES_PASSWORD: R9a0W<5<53
      POSTGRES_DB: postgres
      NATS_ADDRESS: "192.168.0.8:4222"
  query:
    build: "."
    command: "query-service"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: prestixpress
      POSTGRES_PASSWORD: R9a0W<5<53
      POSTGRES_DB: postgres
      NATS_ADDRESS: "192.168.0.8:4222"
      ELASTICSEARCH_ADDRESS: "192.168.0.8:9201"
  nginx:
    build: "./nginx"
    ports:
      -  target: "80"
         host_ip: 127.0.0.1
         published: "8080"
         protocol: tcp
         mode: host
    depends_on:
      - visitplan
      - query
